# -*- coding: utf-8 -*-
"""Atividade4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10c1l0wLgTgdtaiIn7tnFpfNiNl362emW

CENTRO DE EDUCAÇÃO TECNÓLIGA DO AMAZONAS
Curso Técnico em Nível Médio em inteligência Artifical -Turma 2026.1

ALUNOS: RENAN CUNHA

ELIAS SANTOS
"""

print('Curso técnico em Nível Médio de inteligência Artificial - Turma 2026.1')

# O arquivo se chama 'primeiro.py' (este é um comentário, não faz parte do código Python executável)

# As linhas abaixo foram corrigidas:
# Removidos os números de linha e corrigida a sintaxe.
# Assumi que 'nu1' e 'nu2' deveriam ser variáveis inteiras,
# então as inicializei com 0 para que o código seja executável.
# Se a intenção era receber entrada do usuário, poderia ser 'nu1 = int(input("Digite um número:"))'
nu1 = 0
nu2 = 0

print('ola, mundo')

print(5 + 5 - 2)
print(nu1)
print(5**2)
print(nu2)

# Script 1
# Funcção  criada pelo usuário
def dobro(x):
    return x * 2

print(dobro(125))

