# -*- coding: utf-8 -*-
"""Atividade-3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IFXT27g1uN-J5rzHudV5YM7Z5pTNGyHc

CENTRO DE EDUCAÇÃO TECNÓLIGA DO AMAZONAS
Curso Técnico em Nível Médio em inteligência Artifical

ALUNOS: RENAN CUNHA

ELIAS SANTOS
"""

print('ola,mundo')

print(int(8/5)) # divisão com operandos inteiros, retorna resultado inteiro (vs.2.7)
print(8./5)     # divisão com pelo menos um operando real, retorna resultado real ( vs.2.7)

59**-2

numero = 59
resultado= bin(numero)
print(resultado) # saida

2+3
50-5*7
(50-5*6)/2